---
driver:
  name: vagrant
  pre_create_command: cd {{vagrant_root}} && vagrant box update

provisioner:
  name: chef_solo
  require_chef_omnibus: 14

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: stable
    run_list:
      - recipe[ngx::default]
      - recipe[ngx::test]
    attributes: {
      ngx: {
        install: 'stable',
        with_openssl: true,
        with_http2: true,
        with_ipv6: true,
        with_headers_more: true,
        with_status: true,
        with_realip: true,
        with_geoip2: true,
        with_secure_link: true,
        with_njs: true,
        with_gzip_static: true,
        with_brotli: true,
        with_debug: true,
        with_lua: true
      }
    }
  - name: mainline
    run_list:
      - recipe[ngx::default]
      - recipe[ngx::test]
    attributes: {
      ngx: {
        install: 'mainline',
        with_openssl: true,
        with_http2: true,
        with_ipv6: true,
        with_headers_more: true,
        with_status: true,
        with_realip: true,
        with_geoip2: true,
        with_secure_link: true,
        with_njs: true,
        with_gzip_static: true,
        with_brotli: true,
        with_debug: true,
        with_lua: true
      }
    }
